// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_NADK7e-lEI395zh-b04Jv4EoxyvT-ug',
    appId: '1:800276532765:web:b22e72ab74ea6489e000f4',
    messagingSenderId: '800276532765',
    projectId: 'isenecafirebasealejandro',
    authDomain: 'isenecafirebasealejandro.firebaseapp.com',
    storageBucket: 'isenecafirebasealejandro.appspot.com',
    measurementId: 'G-JD08LGG8JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAIXHqPv7cQ7-VVPT7BAvQhI4eT1Q0qZM',
    appId: '1:800276532765:android:f68ce54f90a56167e000f4',
    messagingSenderId: '800276532765',
    projectId: 'isenecafirebasealejandro',
    storageBucket: 'isenecafirebasealejandro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz6EN2SvNDHnSXwSz7V6kLhucPfLXiZUs',
    appId: '1:800276532765:ios:c6bf3d0be7951ec6e000f4',
    messagingSenderId: '800276532765',
    projectId: 'isenecafirebasealejandro',
    storageBucket: 'isenecafirebasealejandro.appspot.com',
    androidClientId: '800276532765-4qbkeqvahj16rim1ikufgvl6in0q3073.apps.googleusercontent.com',
    iosClientId: '800276532765-tbddpmfepv29edk5o05qbu3eu92nk3ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.iseneca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz6EN2SvNDHnSXwSz7V6kLhucPfLXiZUs',
    appId: '1:800276532765:ios:69440e065f1f3530e000f4',
    messagingSenderId: '800276532765',
    projectId: 'isenecafirebasealejandro',
    storageBucket: 'isenecafirebasealejandro.appspot.com',
    androidClientId: '800276532765-4qbkeqvahj16rim1ikufgvl6in0q3073.apps.googleusercontent.com',
    iosClientId: '800276532765-657a5lclakb2nbachvs318bbja28g6is.apps.googleusercontent.com',
    iosBundleId: 'com.example.iseneca.RunnerTests',
  );
}
